### ISSUE TITLE
Drifting Pixels

### ISSUE THREAD

**Issue by Akshu-on-github** [Prathamesh-Shanbhag/Portfolio-Website#15]
### Description

The drifting pixels animation may warrant an epilepsy warning - games with flashing lights, neon colour shifts, drifting snow animations and the like tend to have an epilepsy warning. You never know if a user is sensitive to the same so it's best to stay on the safe side

### Screenshots

![image](https://user-images.githubusercontent.com/61582763/157063945-1b398112-33d3-4f0f-8438-557c7ead8cc6.png)

**Comment by Prathamesh-Shanbhag** [comment]
Hey, can you now check & see if it is still an issue? & is there a warning requirement? @Akshu-on-github

**Comment by Prathamesh-Shanbhag** [comment]
Closed the issue due to inactivity
