### ISSUE TITLE
Animation on website isnt working on Microsoft edge 

### ISSUE THREAD

**Issue by chaudharyjatin115** [Prathamesh-Shanbhag/Portfolio-Website#29]
### Description

Hey there im using microsoft edge v 104 on debian with gnome DE altho it works on chrome here is a screenshot with both browsers running side by side

### Screenshots

![image](https://user-images.githubusercontent.com/21226291/184543537-3fdc69f5-23a0-4b93-acd4-2d671033b41d.png)

**Comment by chaudharyjatin115** [comment]
![image](https://user-images.githubusercontent.com/21226291/184543807-4730acea-669c-42a4-ba11-c76cb50b28f0.png)
the default gnome web browser which uses webkit supports ripple effect but no cybertruck is there

**Comment by Prathamesh-Shanbhag** [comment]
Thank you so much Jatin, I will find a solution to this problem soon!
Would love to hear anyone who wants to contribute - About what the issue could be or how to solve it?
